### PR TITLE
Add onion site for BitMEX.com.

### PR DESCRIPTION
**Pull request by STRML**
We are the owners - added an archive link just in case.

### CODE REVIEW

**Comment by colinmahns** [comment]
Looks good to me, Thanks for the pull request!

**Comment by STRML** [comment]
@colinmahns Looks like this got killed in the refactor.

**Comment by colinmahns** [comment]
It's still here https://github.com/chris-barry/darkweb-everywhere/blob/8124265a4dbc432dd4f33e1e97479752452149c4/deprecated-extension/src/chrome/content/rules/BitMEX.xml 

Looks like it wasn't named with our naming convention of `onion-$site.xml` so I wasn't able to move it when I grabbed {onion,eepsite}-* last night. I'll rename this and move it over later today.

**Comment by STRML** [comment]
Ah, my bad. The guide mentions the naming in the `<ruleset>` tag but not on the file itself. Makes sense though.

**Comment by colinmahns** [comment]
Fixed in this commit! https://github.com/chris-barry/darkweb-everywhere/commit/c3ee480ff73fc4116cf9938d26c0bd13c6779b69

No worries about the wrong filename, the README wasn't as clear as it should be.

**Pull request merged**
