### PR TITLE
Add uploadme.se to darkweb-everywhere

### PR DESCRIPTION
**Pull request by Carlgo11**
I hope it's okay that I verify this myself. I'm one of the creators of Uploadme.se and have set up the hidden service myself.
I don't have any docs to link to.

### CODE REVIEW

**Comment by chris-barry** [comment]
I see you own the site from Github, but is there anyway you can put the name somewhere on your site so it's reproducable without Github? Even a simple text file on your site with "this site is also at http://ufcefwubqauib6of.onion " would be good.

Thanks :smile:

**Comment by Carlgo11** [comment]
@psgs maybe you could add a footnote on the site?

**Comment by psgs** [comment]
@Carlgo11 Sure!

**Comment by Carlgo11** [comment]
@chris-barry done!
This guy is amazing... I mean just look at it!
:cake: to you @psgs!

**Comment by psgs** [comment]
Thankyou @Carlgo11!

**Comment by Carlgo11** [comment]
So @chris-barry is this ready to be merged?

**Comment by colinmahns** [comment]
Sorry for the delay! This must've gotten lost in my inbox. When I'm at keyboard again I will review and merge.

**Pull request merged**
